project_id = "aanollewetntdojenubs"

[functions.domain-status-check]
verify_jwt = false

[functions.luxuryhost-proxy]
verify_jwt = false

[functions.leads-telegram-bot]
verify_jwt = false

[functions.meta-traffic-notify]
verify_jwt = false

[functions.sync-ip-blocklist]
verify_jwt = false

[functions.reminders-telegram-bot]
verify_jwt = false

[functions.reminders-dispatch]
verify_jwt = false

[functions.email-telegram-bot]
verify_jwt = false


